---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ elixir ]

- name: build Elixir LSP server
  shell: |
    git clone --depth 1 --branch {{ elixir_ls_version }} https://github.com/elixir-lsp/elixir-ls.git {{ elixir_ls_dir }}
    cd {{ elixir_ls_dir }}
    mix local.hex --force
    mix local.rebar --force
    mix deps.get
    mix compile
    mix elixir_ls.release -o {{ elixir_ls_build_dir }}
  args:
    creates: "{{ elixir_ls }}"
  tags: [ config, neovim ]

- name: add plugin to Neovim
  blockinfile:
    dest: "{{ neovim_plugin_file }}"
    marker: "-- {mark} ANSIBLE BLOCK: Elixir integration"
    block: |4
        use {
           'mhanberg/elixir.nvim',
            requires = { 'nvim-lua/plenary.nvim' },
            config = [[ require('config.elixir_nvim') ]],
        }
    insertbefore: 'end\) -- END plugins'
  tags: [ config, neovim ]

- name: copy plugin config
  template:
    src: templates/elixir_nvim.j2
    dest: "{{ neovim_plugin_config_dir }}/elixir_nvim.lua"
  tags: [ config, neovim ]

- name: copy filetype config
  copy:
    src: files/ftplugin.vim
    dest: "{{ neovim_config_dir }}/after/ftplugin/elixir.vim"
  tags: [ config, neovim ]

- name: add Elixir source to nvim-cmp config
  blockinfile:
    dest: "{{ neovim_nvim_cmp_config_file }}"
    marker: "-- {mark} ANSIBLE BLOCK: Elixir integration"
    block: |4
                { name = "elixir" },
    insertafter: "sources = {"
  tags: [ config, neovim ]
