---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - software-properties-common

- name: add appimagelauncher ppa to system
  apt_repository:
    validate_certs: no
    repo: 'ppa:appimagelauncher-team/stable'
    state: present
  become: true

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - appimagelauncher
