---

- name: "download {{ rust_version }}"
  get_url: >
    url=https://static.rust-lang.org/dist/{{ rust_build_name }}.tar.gz
    dest={{ rust_download_dir }}/{{ rust_build_name }}.tar.gz
    checksum={{ rust_checksum }}

- name: extract tarball
  unarchive:
    src: "{{ rust_download_dir }}/{{ rust_build_name }}.tar.gz"
    dest: "{{ rust_download_dir }}"
    creates: "{{ rust_download_dir }}"
    copy: no

- name: check current version
  shell: "rustc --version | grep {{ rust_version }}"
  register: result
  changed_when: result.stdout == "0"

- name: run install script
  command: "{{ rust_download_dir }}/{{ rust_build_name }}/install.sh"
  when: result.stdout == "0"
  become: true
