---

- name: install rustup
  shell: "{{ rustup_installer }}"

- name: add Cargo to PATH via fish
  copy:
    src: rust.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/rust.fish"
  when: shell == "fish"
  tags: [ config, fish ]

- name: add Cargo to PATH via zsh
  blockinfile:
    dest: "{{ shell_config_file }}"
    marker: "# {mark} ANSIBLE BLOCK: Rust toolchain"
    block: |
      export PATH="$HOME/.cargo/bin:$PATH"
  when: shell == "zsh"
  tags: [ config, zsh ]

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: add plugin to init.vim
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    marker: "\" {mark} ANSIBLE BLOCK: Rust integration"
    block: |
      Plug 'rust-lang/rust.vim'
    insertbefore: "call plug#end()"
  tags: [ config, neovim ]

- name: install RLS components
  command: |
    rustup component add rls rust-analysis rust-src
  tags: [ config, neovim ]

- name: install CoC RLS extension
  shell: |
    nvim +"CocInstall -sync coc-rls|qa" --headless
  tags: [ config, neovim ]

- name: copy neovim filetype config
  copy:
    src: files/ftplugin.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/ftplugin/rust.vim"
  tags: [ config, neovim ]
