---

- name: install rustup
  shell: "{{ rustup_installer }}"

- name: add Cargo to PATH
  blockinfile:
    dest: "{{ shell_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Rust toolchain"
    block: |
      export PATH="$HOME/.cargo/bin:$PATH"
  tags: [ config ]

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]
