---

- name: install rustup
  shell: "{{ rustup_installer }}"

- name: add Cargo to PATH via fish
  copy:
    src: rust.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/rust.fish"
  when: shell == "fish"
  tags: [ config, fish ]

- name: add Cargo to PATH via zsh
  blockinfile:
    dest: "{{ shell_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Rust toolchain"
    block: |
      export PATH="$HOME/.cargo/bin:$PATH"
  when: shell == "zsh"
  tags: [ config, zsh ]

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: install RLS components
  command: |
    rustup component add rls rust-analysis rust-src
  tags: [config, neovim]

- name: install CoC RLS extension
  shell: |
    nvim +"CocInstall -sync coc-rls|qa" --headless
  tags: [config, neovim]
