---

- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --no-modify-path
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: add Cargo to PATH via fish
  copy:
    src: files/rust.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/rust.fish"
      #dest: "{{ fish_config_dir }}"
  when: shell == "fish"
  tags: [ config, fish ]

- name: add Cargo to PATH via zsh
  blockinfile:
    dest: "{{ shell_config_file }}"
    marker: "# {mark} ANSIBLE BLOCK: Rust toolchain"
    block: |
      export PATH="$HOME/.cargo/bin:$PATH"
  when: shell == "zsh"
  tags: [ config, zsh ]

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]
