---

- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]
