---

- name: install rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --no-modify-path

- name: add Cargo to PATH via fish
  copy:
    src: files/rust.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/rust.fish"
      #dest: "{{ fish_config_dir }}"
  when: shell == "fish"
  tags: [ config, fish ]

- name: add Cargo to PATH via zsh
  blockinfile:
    dest: "{{ shell_config_file }}"
    marker: "# {mark} ANSIBLE BLOCK: Rust toolchain"
    block: |
      export PATH="$HOME/.cargo/bin:$PATH"
  when: shell == "zsh"
  tags: [ config, zsh ]

- name: install toolchain
  shell: "rustup toolchain install {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: set new toolchain as default
  shell: "rustup default {{ version }}"
  when: version != "default"
  tags: [ config ]

- name: install LSP server
  command: |
    rustup component add rust-analyzer
  tags: [ config, neovim ]

- name: add plugin to Neovim
  blockinfile:
    dest: "{{ neovim_plugin_file }}"
    marker: "-- {mark} ANSIBLE BLOCK: Rust integration"
    block: |
      use {
        'simrat39/rust-tools.nvim',
          config = [[ require('config.rust-tools') ]],
      }
    insertafter: "-- [ANSIBLE HOOK]"
  tags: [ config, neovim ]
  notify:
    - update Neovim plugins

- name: copy plugin config
  copy:
    src: files/rust-tools.lua
    dest: "{{ neovim_plugin_config_dir }}"
  tags: [ config, neovim ]
  notify:
    - update Neovim plugins

- name: copy filetype config 
  copy:
    src: files/ftplugin.vim
    dest: "{{ neovim_config_dir }}/after/ftplugin/rust.vim"
  tags: [ config, neovim ]
