---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ fish ]

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ config_dir }}/conf.d"
  tags: [ config ]

- name: install fisher
  shell: |
    source <(curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish) && fisher install jorgebucaran/fisher
  args:
    executable: /bin/bash

- name: install plugins
  shell: |
    fisher install {{ item }}
  with_items:
    - IlanCosman/tide@v6
    - jhillyerd/plugin-git
  tags: [fish]

- name: register fish_path variable
  shell: "which fish"
  register: fish_path
  tags: [ config ]

- name: add fish to allowed shells list
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ fish_path.stdout }}"
  become: true
  tags: [ config ]

- name: set fish as current shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ fish_path.stdout }}"
  become: true
  tags: [ config ]
