---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ fish ]

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ config_dir }}"
    - "{{ config_dir }}/conf.d"
  tags: [ config ]

- name: copy config file
  copy:
    src: files/config.fish
    dest: "{{ config_file }}"
  tags: [ config ]

- include: oh_my_fish.yml
  tags: [ config ]

- name: register fish path as a variable
  shell: "which fish"
  register: fish_path
  tags: [ config ]

- name: add fish to allowed shells list
  lineinfile:
    path: /etc/shells
    state: present
    line: "{{ fish_path.stdout }}"
  become: true
  tags: [ config ]

- name: set fish as current shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ fish_path.stdout }}"
  become: true
  tags: [ config ]
