---

- name: download installer
  get_url:
    url: "{{ omf.installer.src }}"
    dest: "{{ omf.installer.dest }}"
    mode: +x

- name: install
  command: "fish {{ omf.installer.dest }} --path={{ omf.install_path }} --config={{ omf.config_path }}"

- name: clean-up installation file
  file:
    path: "{{ omf.installer.dest }}"
    state: absent

- name: install a decent theme
  shell: "omf install {{ omf.theme }}"
