---

neovim_config_dir: "{{ ansible_env.HOME }}/.config/nvim"
neovim_plugin_dir: "{{ neovim_config_dir }}/plugged"
neovim_vim_plug_dir: "{{ neovim_config_dir }}/autoload"
neovim_plugins:
  # Restores Focus(Lost|Gained) when using iTerm & tmux
  - "sjl/vitality.vim"
  # Fuzzy search
  - { src: "junegunn/fzf", opt: "{ 'do': { -> fzf#install() } }" }
  - "junegunn/fzf.vim"
  # Git diff annotation
  - "airblade/vim-gitgutter"
  # Better status line
  - "itchyny/lightline.vim"
  # Tree browser
  - "lambdalisue/fern.vim"
  - "antoinemadec/FixCursorHold.nvim"
  - "lambdalisue/fern-hijack.vim"
  # Syntax / language packs
  - "sheerun/vim-polyglot"
  # Wrapping strings/tokens
  - "tpope/vim-surround"
  - "tpope/vim-repeat"
  # S-expression support
  - "tpope/vim-sexp-mappings-for-regular-people"
  - "guns/vim-sexp"
  # Language Server Protocol magic
  - { src: "neoclide/coc.nvim", opt: "{'branch': 'release'}" }
  # Elixir integration
  - { src: "elixir-lsp/coc-elixir", opt: "{'do': 'yarn install && yarn prepack'}" }
  - "mhinz/vim-mix-format"
  # Colorschemes
  - "morhetz/gruvbox"
  - "srcery-colors/srcery-vim"
  - "jacoborus/tender.vim"
  - "ayu-theme/ayu-vim"
