---

- name: copy .bashrc
  copy: >
    src=files/.bashrc
    dest={{ bash_config_dir }}/.bashrc
  tags: [ config ]

- name: copy .bash_profile
  copy: >
    src=files/.bash_profile
    dest={{ bash_config_dir }}/.bash_profile
  tags: [ config ]

- name: copy .bash_aliases
  copy: >
    src=files/.bash_aliases
    dest={{ bash_config_dir }}/.bash_aliases
  tags: [ config ]
