---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ curl ]

- name: copy output-formatting template
  copy:
    src: files/.curl_format
    dest: "{{ ansible_env.HOME }}/.curl_format"
  tags: [ config ]
