---

- apt:
    name: curl
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- homebrew:
    name: curl
    state: present
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: copy curl output-formatting template
  copy:
    src: files/.curl_format
    dest: "{{ ansible_env.HOME }}/.curl_format"
  tags: [ config ]
