---

config_dir: "{{ ansible_env.HOME }}/.config/fish"
config_file: "{{ ansible_env.HOME }}/.config/fish/config.fish"

fisher:
  plugins:
    - jorgebucaran/nvm.fish
    - IlanCosman/tide@v6
    - https://github.com/jhillyerd/plugin-git
