---

- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - tasks/vars.yml
  tasks: 
    - name: Install tools via Homebrew
      homebrew: name={{ item }}
      with_items: [ curl, ruby, vim, tmux, sbt, scala, leiningen, rust ]

    - include: tasks/common.yml
