---

- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - tasks/vars.yml
  roles:
      - { role: rust, tags: [ rust ] }
  tasks:
    - name: Install tools via Homebrew
      homebrew: name={{ item }}
      with_items: [ curl, ruby, vim, tmux, sbt, scala, leiningen ]

    - include: tasks/common.yml
