---

- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - tasks/vars.yml
  roles:
    - { role: rust, tags: [ rust ] }
    - { role: sbt, tags: [ sbt ] }
    - { role: java, tags: [ java ] }
    - { role: lein, tags: [ lein ] }
    - common
  tasks:
    - name: Install tools via Homebrew
      homebrew: name={{ item }}
      with_items: [ curl, ruby, vim, tmux, scala ]
