#!/bin/bash

readonly setup_dir="$HOME/src/lowpro"

darwin_deps() {
    local homebrew='https://raw.githubusercontent.com/Homebrew/install/master/install'
    /usr/bin/ruby -e "$(curl -fsSL $homebrew)"
    brew install git ansible
}

linux_deps() {
    sudo apt-get update -y
    sudo apt-get install git ansible -y
}

# Install OS-specific dependancies
case $(uname) in
    Darwin) darwin_deps;;
    Linux ) linux_deps;;
    *     ) echo 'Aborting: Unsupported operating system'
            exit;;
esac

# Clone full repo
git clone https://github.com/mookle/lowpro $setup_dir
cd $setup_dir

# Setup localhost
bin/provision

