#!/bin/bash

readonly setup_dir="$HOME/src/lowpro"

function which_system {
    if [[ $(uname -s) == "Darwin" ]]; then
        echo "Darwin"
    else # Presuming some flavour of Linux
        echo $(cat /etc/issue | awk '{print $1}')
    fi
}

echo "[INFO] Installing system-specific dependancies"
case $(which_system) in
    Darwin)
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew install git ansible
        ;;
    Manjaro)
        sudo pacman -Sy git ansible --noconfirm
        ;;
    Debian)
        sudo apt-get update -y
        sudo apt-get install git ansible -y
        ;;
    *)
        echo 'Aborting: Unsupported operating system'
        exit 1
        ;;
esac

echo "[INFO] Cloning lowpro repo"
git clone https://gitlab.com/mookle/lowpro $setup_dir
cd $setup_dir

while [[ -z $git_user || -z $git_email ]]; do
    echo "[INFO] Additional info needed to configure Git"
    echo -n "Enter username: "
    read git_user
    echo -n "Enter email: "
    read git_email
done

echo "[INFO] Running Ansible playbook"
bin/provision -e git_email=$git_email -e git_user=$git_user

