---

- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - tasks/vars.yml
  roles:
      - { role: rust, tags: [ rust ] }
  tasks:
    - name: Install tools via aptitude
      apt: name={{ item }}
           update_cache=yes
      with_items: [ curl, ruby, vim, tmux, scala ]
      become: true

    - include: tasks/sbt.yml

    - include: tasks/java.yml

    - include: tasks/lein.yml

    - include: tasks/common.yml
