---

- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: "{{ item }}"
      with_first_found:
        - tasks/vars.yml
  roles:
    - { role: rust, tags: [ rust ] }
    - { role: sbt, tags: [ sbt ] }
    - { role: java, tags: [ java ] }
    - { role: lein, tags: [ lein ] }
    - { role: curl, tags: [ curl ] }
    - { role: ruby, tags: [ ruby ] }
    - { role: vim, tags: [ vim ] }
    - { role: tmux, tags: [ tmux ] }
    - { role: scala, tags: [ scala ] }
    - common
