---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - vagrant
      - virtualbox
  when: ansible_system == "Linux"

- name: install via Homebrew cask
  homebrew_cask:
    name: vagrant
    state: present
  when: ansible_os_family == "Darwin"

- name: check for vagrant-vbguest plugin
  shell: vagrant plugin list | grep vagrant-vbguest | wc -m
  register: result
  changed_when: result.stdout == "0"
  tags: [ package ]
