---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package, debian ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package, darwin ]

- name: check for vagrant-vbguest plugin
  shell: vagrant plugin list | grep vagrant-vbguest | wc -m
  register: result
  changed_when: result.stdout == "0"
  tags: [ package ]

- name: install vagrant-vbguest plugin
  command: vagrant plugin install vagrant-vbguest
  when: result.stdout == "0"
  tags: [ package ]
