---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ leiningen ]
  when: ansible_os_family == "Darwin" or ansible_os_family == "Archlinux"

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ leiningen-clojure ]
  when: ansible_os_family == "Debian"
