---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - scala
      - sbt

- name: add plugin to init.vim
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    marker: "\" {mark} ANSIBLE BLOCK: Scala integration"
    block: |
      Plug 'derekwyatt/vim-scala'
    insertbefore: "call plug#end()"
  tags: [ config, neovim ]
