---

- name: remove existing installation
  file:
    path: ~/.asdf
    state: absent

- name: install via Git
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: ~/.asdf
    version: "{{ asdf.version }}"
    single_branch: yes
    update: no
    force: yes

- name: add config (inc completions) to Fish
  blockinfile:
    dest: "{{ shell_config_file }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: asdf config"
    block: |
      source ~/.asdf/asdf.fish
  when: shell == "fish"
  tags: [ config ]

- name: ensure `completions` config directory exists
  file:
    path: ~/.config/fish/completions
    state: directory
  when: shell == "fish"
  tags: [ config ]

- name: symlink config to local installation
  file:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish
    state: link
  when: shell == "fish"
  tags: [ config ]
