---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: add completion to .zshrc
  blockinfile:
    dest: "{{ zsh.config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: asdf completion"
    block: |
      . ~/.asdf/asdf.sh
