---

- homebrew:
    name: asdf
    state: present
  when: ansible_system == "Darwin"

- git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: ~/.asdf
    clone: yes
    version: "{{ asdf.version }}"
    update: no
  when: ansible_system == "Linux"

- name: add asdf completion to Zsh
  blockinfile:
    dest: "{{ shell_config_file }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: asdf completion"
    block: |
      . ~/.asdf/asdf.sh
  when: shell == "zsh"
  tags: [ config ]

- name: add asdf completion to Fish
  blockinfile:
    dest: "{{ shell_config_file }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: asdf completion"
    block: |
      source ~/.asdf/asdf.fish
  when: shell == "fish"
  tags: [ config ]
