---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ zsh ]

- name: create main config file
  blockinfile:
    dest: "{{ config_file }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} ANSIBLE: zsh"
    block: |
      # History file
      HISTFILE=~/.histfile
      HISTSIZE=1000
      SAVEHIST=1000
      setopt appendhistory histignoredups histignorespace

      # No beeps
      unsetopt beep

      # Vi keymap
      bindkey -v

      # Autocomplete
      autoload -Uz compinit
      compinit

      # Preferred editor
      export EDITOR=/usr/bin/nvim
      export VISUAL=/usr/bin/nvim

      # Raspbian SDK / Haskell cross-compilation
      export PATH=~/src/raspbian-sdk/prebuilt/bin:$PATH

      # Set zsh to 256 whilst keeping tmux as screen
      [ $TERM = "xterm" ] && export TERM="xterm-256color"

      # Handy aliases
      [ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
  tags: [ config ]

- name: copy additional config files
  copy:
    src: "files/{{ item }}"
    dest: "{{ config_dir }}/{{ item }}"
  loop:
    - .zprofile
    - .zsh_aliases
  tags: [ config ]

- import_tasks: oh_my_zsh.yml
  tags: [ config ]

- import_tasks: zsh_autosuggestions.yml
  tags: [ config ]

- name: set zsh as default shell
  command: "chsh -s /bin/zsh {{ ansible_env.USER }}"
  become: true
  tags: [ config ]
