---

- name: add to PATH
  file:
    src: "{{ kitty_install_path }}/kitty.app/bin/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
    state: link
  loop:
    - kitty
    - kitten
  tags: [ config ]

- name: integrate with desktop
  include_tasks: desktop.yml
  tags: [ config ]

