---

- name: install via CURL
  shell: |
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n dest={{ kitty_install_path }}

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
