---

- name: install git
  apt:
    name: git
    state: present
    update_cache: yes
  become: true

- name: ensure gem is available
  apt:
    name: ruby
    state: present
    update_cache: yes
  become: true

- name: install ghi
  gem:
    name: ghi
    state: present
  become: true
