---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ git ]

- name: ensure config directory exists
  file:
    path: "{{ git_config_dir }}"
    state: directory
  tags: [ config ]

- name: copy config file
  template:
    src: templates/gitconfig.j2
    dest: "{{ git_config_dir }}/.gitconfig"
  tags: [ config ]

- name: git helper function for zsh
  blockinfile:
    dest: "{{ zsh.config_file }}"
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Git helper functions"
    block: |
      function push() {
        BRANCH=`git branch -l | grep "*" | sed 's/\* //'`
        ARGS=("$@")
        CMD="git push origin $BRANCH $ARGS"
        print -s $CMD
        eval $CMD
      }
      function pull() {
        BRANCH=`git branch -l | grep "*" | sed 's/\* //'`
        ARGS=("$@")
        CMD="git pull origin $BRANCH --rebase $ARGS"
        print -s $CMD
        eval $CMD
      }
    insertafter: EOF
  tags: [ config ]
