---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: ensure config directory exists
  file: >
    path={{ git_config_dir }}
    state=directory
  tags: [ config ]

- name: copy config file
  template: >
    src=templates/gitconfig.j2
    dest={{ git_config_dir }}/.gitconfig
  tags: [ config ]

- name: git helper functions
  blockinfile:
    dest: "~/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Git helper functions"
    block: |
      function push() {
        BRANCH=`git branch -l | grep "*" | sed 's/\* //'`
        ARGS=("$@")
        CMD="git push origin $BRANCH $ARGS"
        history -s $CMD
        (set -x; $CMD)
      }
      function pull() {
        BRANCH=`git branch -l | grep "*" | sed 's/\* //'`
        ARGS=("$@")
        CMD="git pull origin $BRANCH --rebase $ARGS"
        history -s $CMD
        (set -x; $CMD)
      }
