---

# AppImageLauncher is clever enough not to install duplicates
# but this prevents the download and saves time
- name: check for existing installation
  stat:
    path: "{{ obsidian_lockfile }}"
  register: lock

- name: install via appimage
  get_url:
    url: "{{ obsidian_appimage_url }}"
    dest: "{{ ansible_env.HOME }}/obsidian.appimage"
    mode: u+x
  when: lock.stat.exists == false

- name: integrate with desktop
  shell: |
    ail-cli integrate {{ ansible_env.HOME }}/obsidian.appimage
  when: lock.stat.exists == false

- name: create lockfile
  file:
    path: "{{ obsidian_lockfile }}"
    state: touch
  when: lock.stat.exists == false
