---

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: ensure config directory exists
  file:
    path: "{{ haskell_config_dir }}"
    state: directory
  tags: [ config ]

- name: copy config
  copy:
    src: files/.ghci
    dest: "{{ haskell_config_dir }}/.ghci"
  tags: [ config ]

- name: update cabal
  shell: cabal update

- name: install HSpec
  shell: cabal install hspec

- name: copy neovim filetype config
  copy:
    src: files/ftplugin.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/ftplugin/haskell.vim"
  tags: [ config ]
