---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: ensure config directory exists
  file:
    path: "{{ haskell_config_dir }}"
    state: directory
  tags: [ config ]

- name: copy config
  copy:
    src: files/.ghci
    dest: "{{ haskell_config_dir }}/.ghci"
  tags: [ config ]

- name: install HSpec
  shell: cabal install hspec
