---

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: update cabal
  shell: cabal update

- name: install HSpec
  shell: cabal install hspec
