---

- name: install package
  apt:
    name: tmux
    state: present
    update_cache: yes
  become: true

- name: ensure gem is available
  apt:
    name: ruby
    state: present
    update_cache: yes
  become: true
