---

- apt:
    name: tmux
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- homebrew:
    name: tmux
    state: present
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: ensure config directory exists
  file:
    path: "{{ tmux_config_dir }}"
    state: directory
  tags: [ config ]

- name: copy config files
  copy:
    src: "files/{{ item }}"
    dest: "{{ tmux_config_dir }}/{{ item }}"
  loop:
    - .tmux.conf
    - tmux-256color.terminfo
  tags: [ config ]

- name: install terminfo
  command: "tic {{ tmux_config_dir }}/tmux-256color.terminfo"
  tags: [ package ]
