---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ tmux ]

- name: install plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ tpm_install_dir }}"

- name: install plugins
  shell: |
    {{ tpm_install_dir }}/bin/install_plugins
