---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: copy config file
  copy: >
    src=files/.tmux.conf
    dest={{ tmux_config_dir }}/.tmux.conf
  tags: [ config ]

- name: install tmuxinator
  gem: name=tmuxinator
  tags: [ package ]

- name: copy default tmuxinator template
  copy: >
    src=files/tmuxinator_template.yml
    dest={{ tmuxinator_template_dir }}/template.yml
  tags: [ config ]
