---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages: [ tmux ]

- name: ensure config directory exists
  file:
    path: "{{ tmux_config_dir }}"
    state: directory
  tags: [ config ]

- name: copy config files
  copy:
    src: "files/{{ item }}"
    dest: "{{ tmux_config_dir }}/{{ item }}"
  loop:
    - .tmux.conf
    - tmux-256color.terminfo
  tags: [ config ]

- name: install terminfo
  command: "tic {{ tmux_config_dir }}/tmux-256color.terminfo"
  tags: [ package ]
