---

- name: Install tmuxinator
  gem: name=tmuxinator

- name: Pull down dotfile repo
  git: repo=https://github.com/mookle/dotfiles.git
       dest={{ ansible_env.HOME }}/src/dotfiles
       accept_hostkey=yes

- name: Install Python pexpect
  apt: name=python-pexpect
  become: true

- name: Install dotfiles
  expect:
    command: /bin/bash install.sh
    chdir: "{{ ansible_env.HOME }}/src/dotfiles"
    responses:
        (\[y/N\]): "y"

- name: Setup .gitconfig
  lineinfile: >
    dest={{ ansible_env.HOME }}/.gitconfig
    regexp='^(    email = ).*'
    line="\1{{ email }}"
    backrefs=yes
