---

- name: setup core system components
  hosts: localhost
  connection: local
  roles:
    - { role: roles/ssh, tags: ssh }
    - { role: roles/git, tags: git }
    - { role: roles/tmux, tags: tmux }
    - { role: "roles/{{ editor }}", tags: "{{ editor }}" }
    - { role: roles/vagrant, tags: vagrant }
  tags: core

