---

- name: setup core system components
  hosts: localhost
  connection: local
  roles:
    - { role: roles/git, tags: git }
    - { role: roles/tmux, tags: tmux }
    
    - { role: "roles/{{ editor }}", tags: "{{ editor }}" }
  tags: core

