---

- name: install additional packages
  hosts: localhost
  connection: local
  tasks:
    - name: macOS packages
      include_tasks: ../tasks/package_manager.yml
      vars:
        packages: "{{ extras.macos }}"
      when: ansible_system == "Darwin"

    - name: Linux packages
      include_tasks: ../tasks/package_manager.yml
      vars:
        packages: "{{ extras.linux }}"
      when: ansible_system == "Linux"
  tags: extras

