---

- name: setup languages
  hosts: localhost
  connection: local
  roles:
    - { role: roles/asdf, tags: asdf }
  tasks:
    - include_role:
        name: "roles/{{ item.key }}"
        apply:
          tags: "{{ item.key }}"
      vars:
        version: "{{ item.value | default('undefined') }}"
      loop: "{{ languages | dict2items }}"
      tags: "{{ languages.keys() }}"
  tags: languages
