---

- name: setup languages
  hosts: localhost
  connection: local
  roles:
    - { role: roles/asdf, tags: asdf }
  tasks:
    - name: Setup language toolchains
      include_role:
        name: "roles/{{ lang_item.key }}"
        apply:
          tags: "{{ lang_item.key }}"
      vars:
        version: "{{ lang_item.value | default('undefined') }}"
      loop: "{{ languages | dict2items }}"
      loop_control:
        loop_var: lang_item
      tags: "{{ languages.keys() }}"
  handlers:
    - import_tasks: ../roles/neovim/handlers/main.yml
  tags: languages
