# ~/.tmuxinator/template.yml
#
# Basic project setup for local development
#

# Project name
name: template
# Base dir
root: /srv/www/template
# Commandline options
tmux_options: -f ~/.tmux.conf

# Runs at startup
pre: vagrant up > /dev/null &
# Runs on pane creation
pre_window: ~

# Layout
windows:
  - vim: vim .
  - bash: ~
  - vm: vagrant ssh
