---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: [ package ]

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: [ package ]

- name: create config directory
  file: >
    path={{ nvim_config_dir }}
    state=directory
  tags: [ config ]

- name: copy config files
  copy: >
    src=files/
    dest={{ nvim_config_dir }}
  tags: [ config ]
