---

- name: install dependancies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "software-properties-common"
    - "python-pip"
  become: true

- name: add Neovim PPA repo
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: present
  become: true

- name: install Neovim
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: true

- name: install Neovim Python package
  shell: pip2 install --upgrade neovim
