---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - neovim
      - ripgrep

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ neovim_config_dir }}"
    - "{{ neovim_config_dir }}/after/ftplugin"
  tags: [ config ]

- name: copy config
  copy:
    src: "files/config/" # trailing slash means contents get copied, not the dir itself
    dest: "{{ neovim_config_dir }}"
  tags: [ config ]

- name: update git to use neovim
  shell: git config --global core.editor nvim
  tags: [ config ]

- name: setup language integrations
  include_tasks:
    file: "{{ item }}.yml"
  loop:
    - rust
  tags: [ config ]
