---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - neovim
      - ripgrep

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ neovim_config_dir }}"
    - "{{ neovim_plugin_dir }}"
    - "{{ neovim_vim_plug_dir }}"
  tags: [ config ]

- name: copy main config file
  template:
    src: templates/init.vim.j2
    dest: "{{ neovim_config_dir }}/init.vim"
  tags: [ config ]

- name: copy filetype-specific config
  copy:
    src: files/ftplugin
    dest: "{{ neovim_config_dir }}"
  tags: [ config ]

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_vim_plug_dir }}/plug.vim"
  tags: [ config ]

- name: install plugins
  shell: nvim +PlugInstall +qall &
  tags: [ config ]

# FZF added via plugin
- name: add FZF to fish
  copy:
    src: fzf.fish
    dest: "{{ ansible_env.HOME }}/.config/fish/conf.d/fzf.fish"
  when: shell == "fish"
  tags: [ config, fish ]

- name: update git to use neovim
  shell: git config --global core.editor nvim
  tags: [ config ]
