---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - software-properties-common
      - python-pip
      - python3-pip
      - neovim
      - ripgrep
  when: ansible_system == "Linux"

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - neovim/neovim/neovim
      - ripgrep
  when: ansible_system == "Darwin"

# Deoplete requirement
- name: install neovim support for python
  command: pip3 install --user --upgrade pynvim

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ neovim_config_dir }}"
    - "{{ neovim_plugin_dir }}"
    - "{{ neovim_vim_plug_dir }}"
  tags: [ config ]

- name: copy main config file
  template:
    src: templates/init.vim.j2
    dest: "{{ neovim_config_dir }}/init.vim"
  tags: [ config ]

- name: copy filetype-specific config
  copy:
    src: files/ftplugin
    dest: "{{ neovim_config_dir }}"
  tags: [ config ]

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_vim_plug_dir }}/plug.vim"
  tags: [ config ]

- name: install plugins
  shell: nvim +PlugInstall +qall &
  tags: [ config ]

- name: add FZF to bash / zsh
  blockinfile:
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Fuzzy search"
    block: |
      [ -f ~/.fzf.bash ] && source ~/.fzf.bash
      export FZF_DEFAULT_COMMAND='rg --files --follow --color never'
  loop:
    - .bashrc
    - .zshrc
  tags: [ config ]

- name: update git to use neovim
  command: git config --global core.editor $(which nvim)
