---

- name: install via package manager
  include_tasks: package_manager.yml
  vars:
    packages:
      - neovim
      - ripgrep

- name: ensure config directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ neovim_config_dir }}"
    - "{{ neovim_config_dir }}/after/ftplugin"
  tags: [ config ]

- name: copy config
  copy:
    src: "files/config/" # trailing slash means contents get copied, not the dir itself
    dest: "{{ neovim_config_dir }}"
  tags: [ config ]

    #- name: install plugins
    #shell: nvim +PackerSync +qall &
    #tags: [ config ]

- name: update git to use neovim
  shell: git config --global core.editor nvim
  tags: [ config ]

- name: import vars from role
  include_vars:
    file: defaults/main.yml
    name: tmp_vars
  tags: always

- name: set facts for later roles
  set_fact:
    neovim_plugin_file: "{{ tmp_vars['neovim_config_dir'] }}/lua/plugins.lua"
    neovim_plugin_config_dir: "{{ tmp_vars['neovim_config_dir'] }}/lua/config"
    neovim_config_dir: "{{ neovim_config_dir }}"
  tags: always

- debug:
    var: "{{ item }}"
  loop:
    - neovim_config_dir
    - neovim_plugin_file
    - neovim_plugin_config_dir
  tags: always
